file_paths = {'eng_train': './data/eng/eng_train.conllu',
		'eng_dev': './data/eng/eng_dev.conllu',
		'eng_test': './data/eng/eng_test.conllu',
		'eng_word_emb': './data/eng/eng_word_embeddings_50',
		'eng_train_children': './data/eng/eng_train_children',
		'eng_dev_children': './data/eng/eng_dev_children',
		'eng_test_children': './data/eng/eng_test_children',
		'es_train': './data/es/es_gsd-ud-train.conllu',
		'es_dev': './data/es/es_gsd-ud-dev.conllu',
		'es_test': './data/es/es_gsd-ud-test.conllu',
		'es_word_emb': './data/es/es_word_embeddings_50',
		'es_train_children': './data/es/es_train_children',
		'es_dev_children': './data/es/es_dev_children',
		'es_test_children': './data/es/es_test_children',
		'pos_emb': './data/pos_embeddings_50',
		'deprel_emb': './data/deps_embeddings_50',
		'left_labels': './data/left_labels',
		'right_labels': './data/right_labels',
		'shift_label': './data/shift',
		}


